#!/bin/bash
download_url='ftp://ftp.mplayerhq.hu/MPlayer/releases/MPlayer-1.1.1.tar.xz'
src_directory=`basename $download_url .tar.xz`

download=true
if [ -d "$src_directory" ]; then
  read -p "Source code directory already exists. Download again?" yn
  if [ "$yn" != "y" ]; then
    download=false
  fi
fi

if [ "$download" = true ]; then
  echo "Downloading source code."
  curl -sS $download_url | tar -xvf -
  if [ ! -d "$src_directory" ]; then
    echo "Download failed."
    exit 1
  fi
fi

cd $src_directory

cv_file='libvo/vo_corevideo.m'
gl_line='#include <OpenGL/gl.h>'
find_result=`grep "$gl_line" "$cv_file"`

echo "Patching $cv_file."
if [ "$find_result" == "" ]; then
  csv_line='#include <CoreServices/CoreServices.h>'
  find_result=`cat -n "$cv_file" | grep "$csv_line" | cut -f 1`
  line_num=`expr $find_result + 1`
  sed -i '' "${line_num}i\\
$gl_line
" $cv_file

else
  echo "Already patched."
fi

